##common
spring:
  config:
    import: file:.env[.properties]

application:
  name: Bookmark

---
#local
spring:
  config:
    activate:
      on-profile: local
h2:
  console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookmark
    username: sa
  jpa:
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8081
jwt:
  secret-key: JSON_WEB_TOKEN_SECRET_KEY_FOR_LOCAL_PROFILE
---
###dev
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080