##common
spring:
  config:
    import: file:.env[.properties]

application:
  name: Bookmark

host:
  email: ${NAVER_ID}
  password: ${NAVER_PASSWORD}

jwt:
  access-expiration: 1800000
  password-expiration: 300000
---
#local
spring:
  config:
    activate:
      on-profile: local
h2:
  console:
    enabled: true
    path: /h2-console
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:bookmark
    username: sa
  jpa:
    show_sql: true
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
server:
  port: 8081
jwt:
  access-secret-key: ${JWT_TOKEN_ACCESS_SECRET_KEY_LOCAL}
  password-secret-key: ${JWT_TOKEN_PASSWORD_SECRET_KEY_LOCAL}

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type.descriptor.sql.BasicBinder: trace
---
###dev
spring:
  config:
    activate:
      on-profile: dev

server:
  port: 8080

jwt:
  access-secret-key: ${JWT_TOKEN_ACCESS_SECRET_KEY_DEV}
  password-secret-key: ${JWT_TOKEN_PASSWORD_SECRET_KEY_DEV}